notifications:
  email: false
git:
  quiet: true
  depth: 1
env:
  global:
  - TERM=dumb
language: java
jdk: openjdk8
install: true
jobs:
  include:
  - stage: test
    jdk: openjdk8
    name: test jdk8
    script:
      - ./mvnw -U
      - java -jar guava-eventbus/target/*-all.jar
      - java -jar publish-subscribe/target/*-all.jar
      - java -jar reflections-class-path-scanning-annotation-type/target/*-all.jar
      - java -jar spring-class-path-scanning-annotation-type/target/*-all.jar
  - stage: test
    jdk: openjdk8
    name: check updates jdk8
    script: ./mvnw versions:display-property-updates
  - stage: test
    jdk: openjdk11
    name: test jdk11
    script: ./mvnw -U
  - stage: test
    jdk: openjdk11
    name: check updates jdk11
    script: ./mvnw versions:display-property-updates
cache:
  pip: true
  packages: true
  directories:
  - ~/.m2
