dist: xenial
notifications:
  email: false
git:
  quiet: true
  depth: 1
env:
  global:
  - TERM=dumb
language: java
jdk: openjdk8
install: true
script:
### JDK8 ###
- ./mvnw clean test -U
cache:
  pip: true
  packages: true
  directories:
  - ~/.m2
