name: CI
on: [push]
env:
  CI: 'true'
jobs:
  tests:
    strategy:
      matrix:
        java: [1.8,11,14]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: ci tests java-${{ matrix.java }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - run: cd $GITHUB_WORKSPACE && ./mvnw
